version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: cosai
      POSTGRES_USER: cosaiuser
      POSTGRES_PASSWORD: cosaipass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cosaiuser -d cosai"]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build: .
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgresql://cosaiuser:cosaipass@db:5432/cosai
      - DEBUG=true
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./images:/app/images

volumes:
  pgdata: 